# untested
version: '2'

services:
  woderb.core:
    image: registry.cn-hangzhou.aliyuncs.com/zicjin/woderb.core
    ports:
      - "8080:80"
  mongo1:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - /volumes/mdata:/data/db
    command: "--storageEngine=wiredTiger"
  consul1:
    image: consul
    ports:
      - "8400:8400"
      - "8500:8500/tcp"
      - "53:8600/udp"
    volumes:
      - /volumes/cdata:/consul/data
      - /volumes/cconfig:/consul/config
    command: "agent -server -node=n1 -bootstrap -ui -client='0.0.0.0' -bind='{{ GetPrivateIP }}'"
  nginx1:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - /root/woderb.web/dist:/usr/share/nginx/www:ro
      - /root/woderb.weather:/usr/share/nginx/weather:ro
      - /root/woderb.web/nginx.conf:/etc/nginx/nginx.conf:ro